name: point_treat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0-152

dependencies:
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_slidable: ^3.1.0
  go_router: ^14.1.0
  hooks_riverpod: ^2.5.1
  point_treat_view_model:
    path: packages/point_treat_view_model
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.10
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  melos: ^6.0.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0


flutter:
  uses-material-design: true
