name: CI/CD

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ContinuousIntegration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install fvm
        run: curl -fsSL https://fvm.app/install.sh | bash

      - name: setup flutter
        run: fvm install

      - name: Install dependencies
        run: fvm flutter pub get

      - name: Analyze project source
        run: fvm flutter analyze

      - name: Run tests
        run: fvm flutter test
